---
apiVersion: v1
kind: Pod
metadata:
  name: appserver
  labels:
    environment: dev
    app: nginx
    ver: v1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
